---
version: '3'
services:
  # The environment variable "TAG" is used throughout this file to
  # specify the version of the images to run. The default is set in the
  # '.env' file in this folder. It can be overridden with any normal
  # technique for setting environment variables, for example:
  #
  #   TAG=5.3.0 docker-compose up
  #
  # REF: https://docs.docker.com/compose/compose-file/#variable-substitution
  #
  # Also to be sure to set ELASTIC_VERSION variable. For released versions,
  # ${TAG} and ${ELASTIC_VERSION} will be identical, but for pre-release
  # versions, ${TAG} might contain an extra build identifier, like
  # "5.4.0-a80c820b", so a full invocation might look like:
  #
  #   ELASTIC_VERSION=5.5.2 TAG=5.5.2 docker-compose up
  #
  mysql:
    image: mysql
    ports: ['127.0.0.1:3306:3306']
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lt_tmview
    volumes:
     - ./db-dump:/docker-entrypoint-initdb.d
    networks: ['stack']

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports: ['127.0.0.1:9200:9200']
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    # Provide a simple pipeline configuration for Logstash with a bind-mounted file.
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./lib/mysql-connector-java-5.1.44-bin.jar:/usr/share/logstash/mysql-connector-java-5.1.44-bin.jar
    networks: ['stack']
    depends_on: ['elasticsearch','mysql']

networks: {stack: {}}
